### PR TITLE
WIP: BandedBlockBandedMatrix can parameterize storage

### PR DESCRIPTION
**Pull request by mdavezac**
But no tests for anything but PseudoBlockMatrix yet.

### CODE REVIEW

**Comment by mdavezac** [comment]
@dlfivefifty, the parameterization is pretty much done. I'll rebase on master once master passes on Travis. It can be tested by susbtituting `PseudoBlockArray` with `BlockArray`.

I think the next step will be to try and figure out how to do matrix * matrix and matrix * vector. At least the first one fails since it requires `strides`, which problably does not make sense in the case of a `BlockArray`.

I noticed that "test_broadcasting.jl" is not in "runtests.jl". Just putting it out there if it got lost at some point.

**Comment by dlfivefifty** [comment]
I merged the changes to master back here, and tests should pass when on BlockArrays and BandedMatrices master.

**Comment by dlfivefifty** [comment]
I've added an example using SharedArrays for building matrices. (CLArrays.jl hasn't been updated to 1.0 and I don't have access to a CUDA device.) The current SharedArrays code is much slower than the  Serial one, but this is perhaps because I'm not specifying `localindices`.

**Comment by dlfivefifty** [comment]
Now that I've merged (and squashed) the changes introduced here, this PR probably needs to be rebased.

**Pull request closed without merging**
