### PR TITLE
Support block banded cholesky

### PR DESCRIPTION
**Pull request by dlfivefifty**

### CODE REVIEW

**Comment by dlfivefifty** [comment]
@TSGut @MikaelSlevinsky This might be useful especially for 2D stuff. Should be fairly straightforward to get it working adaptively as well.

FYI for 2D finite-difference matrix it roughly matches the speed of UMFPack which I think is a "success":
```julia
julia> @time cholesky(Symmetric(Δ));
  0.360270 seconds (359.21 k allocations: 204.490 MiB)

julia> @time cholesky(sparse(Δ));
  0.379772 seconds (5.49 k allocations: 88.902 MiB)
```

**Comment by dlfivefifty** [comment]
Actually... this has a different complexity than UMF pack so when `n` becomes large UMFPack is still much faster...

**Comment by MikaelSlevinsky** [comment]
Should I retract my rocket?

**Comment by dlfivefifty** [comment]
Probably... at least until we add multithreading. (Actually that might be a bigger part of why UMFPack seems to have better complexity.)

**Pull request merged**
